trigger:
- master
- release/*

jobs:
- job: Build
  pool:
    vmImage: 'Ubuntu-18.04'
  variables:
    - group: wayland
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 12
  - task: DownloadSecureFile@1
    name: nrfjprogLinux
    inputs:
      secureFile: "nrfjprog-10.7.0-linux_x64.tar.gz"
    condition: eq(variables['INTERNAL'], 'true')
    displayName: 'Donwload internal nrfjprog for release'
  - bash: |
      set -o errexit -o pipefail
      export LOCAL_NRFJPROG_PATH=$(nrfjprogLinux.secureFilePath)
      export ENABLE_DRAFT_TEST=true
      export NODE_PRE_GYP_GITHUB_TOKEN=$(WAYLAND_GITHUB_TOKEN)
      npm config set strict-ssl false
      npm config set //npm.nordicsemi.no/:_authToken $(WAYLAND_NPM_TOKEN_INTERNAL)
      npm config set registry https://npm.nordicsemi.no/
      npm config set @babel:registry https://registry.npmjs.org/
      npm config set @cnakazawa:registry https://registry.npmjs.org/
      npm config set @jest:registry https://registry.npmjs.org/
      npm config set @protobufjs:registry https://registry.npmjs.org/
      npm config set @serialport:registry https://registry.npmjs.org/
      npm config set @types:registry https://registry.npmjs.org/
      npm config set glob:registry https://registry.npmjs.org/
      npm config set string_decoder:registry https://registry.npmjs.org/
      npm i
      npm run rollup
    condition: eq(variables['INTERNAL'], 'true')
    displayName: 'Build with internal release'
  - script: |
      set -o errexit -o pipefail
      npm i
      npm run rollup
    condition: ne(variables['INTERNAL'], 'true')
    displayName: 'Build'
  - bash: |
      set -o errexit -o pipefail
      npm pack
      mkdir -p ./build/stage
      mv *.tgz ./build/stage
    displayName: 'Pack and move package'
  - task: PublishPipelineArtifact@1
    inputs:
      path: $(System.DefaultWorkingDirectory)/build/stage
    displayName: 'Publish artifacts'
